# This file was generated by GoReleaser. DO NOT EDIT.
class Eosc < Formula
  desc "Cross-platform EOS command-line swiss-army-knife"
  homepage "https://eosc.app/"
  version "1.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/eoscanada/eosc/releases/download/v1.4.0/eosc_1.4.0_macOS_x86_64.tar.gz"
    sha256 "128618092791b1ed5a6840baf05ceb31a68f72f6dbb075b14d867c9303b72140"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/eoscanada/eosc/releases/download/v1.4.0/eosc_1.4.0_linux_x86_64.tar.gz"
      sha256 "b3a60641b8487bce28b7f58f7f233f0c59b88f7bacf6369e81c781872c677434"
    end
  end

  def install
    bin.install "eosc"
  end
end
